[package]
name = "attributes-proceduralMacros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = "0.12.1"
ic-cdk-macros = "0.8.4"
candid = "0.10.2" 
serde = "1.0"
serde_derive = "1.0"